version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  # node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      # - node/install-packages:
      #     pkg-manager: yarn
      #     cache-key: "yarn.lock"
  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          DB_HOST: db-test    #127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_USER: yuki
          MYSQL_DB: golfour_test
    # environment:
    #   BUNDLE_JOBS: "3"
    #   BUNDLE_RETRY: "3"
    #   PGHOST: 127.0.0.1
    #   PGUSER: circleci-demo-ruby
    #   PGPASSWORD: ""
    #   RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      # - node/install-packages:
      #     pkg-manager: yarn
      #     cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
